# <b>DSA STARTS FROM HERE

### <i>This was the first question about the dsa in which we had solved the good problem of finding leaders in arrays

In [1]:
import numpy as np  

In [2]:

def leader_tell(arr):
    arr = np.array(arr)
    leaders = [arr[-1]]
    
    for i in range(len(arr)-2,-1,-1):
        if arr[i]>leaders[-1]:
            leaders.append(arr[i])
    leaders.reverse()
    return np.array(leaders)
arr =    np.array([16, 17, 4, 3, 5, 2])
print("The leaders are",leader_tell(arr))
    

The leaders are [17  5  2]


### <i>Largest Number in The Array

In [3]:
arra =np.array( [12, 45, 78, 34, 56, 23, 89])
arra.max()

def find_largest_element(arr):
    largest = arr[0]
    for i in range(1, len(arr)):
        if arr[i] > largest:
            largest = arr[i]
    return largest

arr = np.array([12, 45, 78, 34, 56, 23, 89])
find_largest_element(arr)



89

### <i>Second Largest Element checker 

In [4]:
def second_largest_tell(arr):
    #it our choice to continue
    largest = arr[0]
    second_largest = [-1]
    for i in range(1,len(arr)):
        if arr[i]>largest:
            second_largest = largest
            largest= arr[i]
    return largest,second_largest
arra1 = np.array([12, 45, 7, 34, 56, 23, 89])
print("The desired outcome would be",second_largest_tell(arra1))

The desired outcome would be (89, 56)


NINJA and the Second Order Element 

In [5]:
def desired_output(arr):
    #it our choice to continue
    largest = arr[0]
    second_largest = [-1]
    for i in range(1,len(arr)):
        if arr[i]>largest:
            second_largest = largest
            largest= arr[i]
    smallest = arr[0]
    second_smallest = arr[-1]
    for v in range(1,len(arr)):
        if arr[v]<smallest:
            second_smallest = smallest
            smallest = arr[v]
    # print(second_smallest)       
    arrs = np.array([second_largest,second_smallest])
    return arrs




arra1 = np.array([12, 45, 7, 34, 56, 23, 89])
print("The desired outcome would be",desired_output(arra1))

The desired outcome would be [56 12]


### <i>Left Rotate the array by one place

In [6]:
class Solution:
    def left_rotate(arr):
        temp_element = arr[0]
        for i in range(1,len(arr)):
            arr[i-1] = arr[i]
        arr[(len(arr))-1] = temp_element
        return arr
array_1 = np.array([1,2,3,4,5,6])
clss_solution = Solution()
result = Solution.left_rotate(arr =array_1)
print(result)

[2 3 4 5 6 1]


### <i>Left Rotate the array by D-places

#### <b> Doubt

In [33]:
class Solution1:
    @staticmethod
    def left_rotater_d(arr,d):
        d_place = arr[:d].copy()
        print(d_place)
        for i in range(d,len(arr)):
            arr[i-d] = arr[i]
        
        for i in range(len(arr) - d, len(arr)):
                arr[i] = d_place[(i - (len(arr) - d))]
                    
        return arr


arra1 = np.array([1, 2, 3, 4, 5, 6, 7])
class_solution1 = Solution1()
result1 = class_solution1.left_rotater_d(arr=arra1, d=2)
print(result1)

            

[1 2]
[3 4 5 6 7 1 2]


#### <i>Moving all Zeros to the End of the array

In [53]:
class Solutin2:
    @staticmethod
    def zero_last_push(arr):
        leader = []
        for i in arr:
            if  i> 0:
                leader.append(i)
        for i in arr:
            if i ==0:
                leader.append(i)
        return np.array(leader)
arr1= np.array([1,2,0,0,4,0,5,2,])
s1 = Solutin2()
q  =s1.zero_last_push(arr1)
q



array([1, 2, 4, 5, 2, 0, 0, 0])