In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [18]:
print(np.__version__)
print(a.dtype)
print(type(a))

1.26.4


In [5]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

my revision


In [37]:
ar_zero = np.zeros((5,4)) #with zero array return hoga 
ar_one = np.ones((1,5))  #with 1's array return hoga
ar_empt = np.empty((3,4)) #back memory mae jo bhi save hoga vi isme ata h
# ar_empt
ar_zero
ar_one

array([[1., 1., 1., 1., 1.]])

In [11]:
# ae = np.random.randn(6,6) #-ve to +ve har values ko return karengi
# ae
aee =np.random.randint(1,6,10) # (start_value,stop_value,total_values)
# aee
# print(aee.dtype)
ret = np.ones((5,5)) # 5 X 5 ki matrix bnane k liy
ter = np.eye((5)) # identity matrix
added = np.add(ret,ter) # arithematic operation
# added
# print(np.char.title(["python", "numpy"])) #to give tittle
se = np.char.split(("are you guys coming to party"))    # split kar dega list mae
# print(se)
# print(np.char.strip(["hey","hola","frah"],"h")) #removes the starting and trailing letter from arrays
# print(np.char.join([":","-"],["dirt","mud"])) #yae  particular word ko add kar deta h

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],dtype = 'i4');#print(arr[0:2, 2])
arr = np.array([1.1, 2.1, 3.1]);newarr = arr.astype('i')
#print(newarr);print(newarr.dtype)

#astype() is function creates a copy and allows you to change datatype and let you operate on this 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3);print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]]);newarr = arr.reshape(-1);#print(newarr)
#arrays are same iterables as same as other datatypes

# arr = np.array([[1, 2, 3], [4, 5, 6]])
# for x in arr:
#   print(x)

# arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# for x in arr:
#   for y in x:
#     for z in y:
#       print(z)
varr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(varr):
  print(x)
      


1
2
3
4
5
6
7
8


In [53]:
ret.ndim
ret.itemsize
ret.shape


(5, 5)

In [54]:
# help(ret.itemsize)
help(np.ndim)

Help on _ArrayFunctionDispatcher in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0

