In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(np.__version__)
print(a.dtype)
print(type(a))

1.26.4
int32
<class 'numpy.ndarray'>


In [4]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

my revision


In [5]:
ar_zero = np.zeros((5,4)) #with zero array return hoga 
ar_one = np.ones((1,5))  #with 1's array return hoga
ar_empt = np.empty((3,4)) #back memory mae jo bhi save hoga vi isme ata h
# ar_empt
ar_zero
ar_one

array([[1., 1., 1., 1., 1.]])

In [6]:
# ae = np.random.randn(6,6) #-ve to +ve har values ko return karengi
# ae
aee =np.random.randint(1,6,10) # (start_value,stop_value,total_values)
# aee
# print(aee.dtype)
ret = np.ones((5,5)) # 5 X 5 ki matrix bnane k liy
ter = np.eye((5)) # identity matrix
added = np.add(ret,ter) # arithematic operation
# added
# print(np.char.title(["python", "numpy"])) #to give tittle
se = np.char.split(("are you guys coming to party"))    # split kar dega list mae
# print(se)
# print(np.char.strip(["hey","hola","frah"],"h")) #removes the starting and trailing letter from arrays
# print(np.char.join([":","-"],["dirt","mud"])) #yae  particular word ko add kar deta h

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],dtype = 'i4');#print(arr[0:2, 2])
arr = np.array([1.1, 2.1, 3.1]);newarr = arr.astype('i')
#print(newarr);print(newarr.dtype)

#astype() is function creates a copy and allows you to change datatype and let you operate on this 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3);print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]]);newarr = arr.reshape(-1);#print(newarr)
#arrays are same iterables as same as other datatypes

# arr = np.array([[1, 2, 3], [4, 5, 6]])
# for x in arr:
#   print(x)

# arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# for x in arr:
#   for y in x:
#     for z in y:
#       print(z)
varr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# for x in np.nditer(varr):
#   print(x)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# for x in np.nditer(arr[:, ::2]):
#   print(x)
for id ,x  in np.ndenumerate(arr):
  print(id,x)                 # to check the index with the array in respect ot both of them

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [8]:
ew = np.array([10,20,30])
ut = np.array([100,200,300])
rwe = np.concatenate((ew,ut),axis = 0)

print("\n")

gr = np.arange(16,0,-1).reshape(4,4)
rg = np.arange(26,10,-1).reshape(4,4)
rgr = np.concatenate((gr,rg),axis = 0)
rgr

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1],
       [26, 25, 24, 23],
       [22, 21, 20, 19],
       [18, 17, 16, 15],
       [14, 13, 12, 11]])

In [9]:
tr=np.array([[1,2,3],[4,5,6]])
rt = np.array([[10,20,30],[100,200,300]])
qq = np.concatenate((rt,tr),axis = 0)         #it will join the two arrays

yu = np.array([1000,2000,3000])
uy = np.array([9000,8000,7000])
# uyu = np.stack((yu,uy),axis=1)  #it concatenate/stack  in default manner
uyu = np.hstack((yu,uy)) # in a row it will stack
uyu = np.vstack((yu,uy)) # in a column it will stack
uyu

array([[1000, 2000, 3000],
       [9000, 8000, 7000]])

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr,4,axis=0)
newarr


swwe = np.array([1,2,3,4,5,6,7,8])
wq = np.where(swwe%2==0)            # searching in arrays
wq

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7,side='right')         #binary search in the array
x


2

In [16]:
codwe = np.array([True,False,True])
print(np.sort(codwe))


grf = np.array([[3,2,4],[5,0,1]])
print(np.sort(grf))

[False  True  True]
[[2 3 4]
 [0 1 5]]


In [12]:
ret.ndim
ret.itemsize
ret.shape



(5, 5)

In [13]:
# help(ret.itemsize)
help(np.ndim)

Help on _ArrayFunctionDispatcher in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0

