In [1]:
import numpy as np

Write a code snippet to create a 3x3 numpy array with values ranging from 1 to 9 and iterate through each element using nested loops


In [2]:
a = np.arange(0,9)
a.reshape(3,3)
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8


Create a numpy array of shape (2, 4) filled with zeros and another array of shape (3, 3) filled with ones. Print their data types and shapes.

In [3]:
arr = np.zeros((2,4))
# arr.reshape(2,4)
varr = np.ones((3,3))
print(varr)
print(arr)
print("\n")
print(varr.dtype,varr.shape)
print(arr.dtype,arr.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


float64 (3, 3)
float64 (2, 4)


Given a numpy array str_arr containing strings, write code to convert each string to title case and print the result.

In [4]:
str_arr = np.char.array([["hello","byy"],["gm","gn"]])
print(str_arr.title())


[['Hello' 'Byy']
 ['Gm' 'Gn']]


Create a numpy array containing float values ranging from 1.1 to 5.5. Use astype() to convert it to an array of integers and print the result.

In [5]:
der = np.arange(1.1,5.5)
fer = der.astype(dtype='int64')
#fer
#hello

Define a numpy array arr of shape (4, 6) filled with values from 1 to 24. Reshape it to a 2x12 array and print the result.

In [6]:
se = np.arange(1,25).reshape(4,6)
de = se.reshape(2,12)
print(de)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


Compare the performance of iterating through a numpy array using nested loops versus using np.nditer() for a large array (e.g., shape (1000, 1000)).


In [ ]:
we = np.arange(1,1000001).reshape(1000,1000)
for i in np.nditer(we):
    print(i)

Create a 4x4 identity matrix using numpy functions only. Then, multiply it by a randomly generated 4x4 matrix and print the result.


In [8]:
re = np.eye(4,4)
er = np.random.random_sample((4,4))
qw =re.__mul__(er)
qw


array([[0.19142525, 0.        , 0.        , 0.        ],
       [0.        , 0.28911197, 0.        , 0.        ],
       [0.        , 0.        , 0.34955532, 0.        ],
       [0.        , 0.        , 0.        , 0.76721057]])

 Given an array `arr` containing the temperature data of a city for a week (7 days), split it into three parts representing morning, afternoon, and evening temperatures respectively. Print each part separately
 [20, 22, 24, 26, 28, 30, 29]
 

In [26]:

arr = np.array([20, 22, 24, 26, 28, 30, 29])
morning_temperatures, afternoon_temperatures, evening_temperatures = np.array_split(arr, [2, 4])
print("Morning temperatures:", morning_temperatures)
print("Afternoon temperatures:", afternoon_temperatures)
print("Evening temperatures:", evening_temperatures)


Morning temperatures: [20 22]
Afternoon temperatures: [24 26]
Evening temperatures: [28 30 29]


Consider an array `arr` representing the quarterly sales data of a company, where each row corresponds to a quarter and each column represents different product categories. Split this array into three parts representing sales data for each product category. Print each part separately.

`After splitting`,<br>
you should have:<br>
Sales data for Product Category 1: [[100, 150, 200], [120, 180, 220]]<br>
Sales data for Product Category 2: [[90, 160, 210], [110, 170, 230]]<br>
Sales data for Product Category 3: Not specified in the sample, but you should provide a similar split.<br>

In [104]:
arr = np.array([[100, 150, 200], [120, 180, 220], [90, 160, 210], [110, 170, 230]])
fr,rf,gf = np.array_split(arr,[2,4])
print("catgory1 \n",fr)
print("category2 \n",rf)
print("category3 \n",gf)

catgory1 
 [[100 150 200]
 [120 180 220]]
category2 
 [[ 90 160 210]
 [110 170 230]]
category3 
 []


 Given an array `arr` representing the student scores in a class test, split it into 4 parts representing different sections of the class. Then, for each section, find the position where the score 7 fails, if it exists.
 

In [158]:
arr = np.array([7, 8, 6, 7, 9, 7, 8, 5, 7, 7])


In [140]:
help(np.array_split)

Help on _ArrayFunctionDispatcher in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.
    
    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
    [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
    
    >>> x = np.arange(9)
    >>> np.array_split(x, 4)
    [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

