In [2]:
import numpy as np

ques 1


In [11]:
a = np.arange(0,9)
a.reshape(3,3)
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8


In [20]:
arr = np.zeros((2,4))
# arr.reshape(2,4)
varr = np.ones((3,3))
print(varr)
print(arr)
print("\n")
print(varr.dtype,varr.shape)
print(arr.dtype,arr.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


float64 (3, 3)
float64 (2, 4)


In [22]:
str_arr = np.char.array([["hello","byy"],["gm","gn"]])
print(str_arr.title())


[['Hello' 'Byy']
 ['Gm' 'Gn']]


In [35]:
der = np.arange(1.1,5.5)
fer = der.astype(dtype='int64')
#fer


array([1.1, 2.1, 3.1, 4.1, 5.1])