In [2]:
import numpy as np

Write a code snippet to create a 3x3 numpy array with values ranging from 1 to 9 and iterate through each element using nested loops


In [11]:
a = np.arange(0,9)
a.reshape(3,3)
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8


Create a numpy array of shape (2, 4) filled with zeros and another array of shape (3, 3) filled with ones. Print their data types and shapes.

In [20]:
arr = np.zeros((2,4))
# arr.reshape(2,4)
varr = np.ones((3,3))
print(varr)
print(arr)
print("\n")
print(varr.dtype,varr.shape)
print(arr.dtype,arr.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


float64 (3, 3)
float64 (2, 4)


Given a numpy array str_arr containing strings, write code to convert each string to title case and print the result.

In [22]:
str_arr = np.char.array([["hello","byy"],["gm","gn"]])
print(str_arr.title())


[['Hello' 'Byy']
 ['Gm' 'Gn']]


Create a numpy array containing float values ranging from 1.1 to 5.5. Use astype() to convert it to an array of integers and print the result.

In [3]:
der = np.arange(1.1,5.5)
fer = der.astype(dtype='int64')
#fer
#hello

Define a numpy array arr of shape (4, 6) filled with values from 1 to 24. Reshape it to a 2x12 array and print the result.

In [44]:
se = np.arange(1,25).reshape(4,6)
de = se.reshape(2,12)
print(de)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


Compare the performance of iterating through a numpy array using nested loops versus using np.nditer() for a large array (e.g., shape (1000, 1000)).


In [ ]:
we = np.arange(1,1000001).reshape(1000,1000)
for i in np.nditer(we):
    print(i)

Create a 4x4 identity matrix using numpy functions only. Then, multiply it by a randomly generated 4x4 matrix and print the result.


In [75]:
re = np.eye(4,4)
er = np.random.random_sample((4,4))
qw =re.__mul__(er)
qw


array([[0.48604758, 0.        , 0.        , 0.        ],
       [0.        , 0.33922787, 0.        , 0.        ],
       [0.        , 0.        , 0.9385854 , 0.        ],
       [0.        , 0.        , 0.        , 0.4891328 ]])