In [1]:
import numpy as np

Write a code snippet to create a 3x3 numpy array with values ranging from 1 to 9 and iterate through each element using nested loops


In [2]:
a = np.arange(0,9)
a.reshape(3,3)
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8


Create a numpy array of shape (2, 4) filled with zeros and another array of shape (3, 3) filled with ones. Print their data types and shapes.

In [3]:
arr = np.zeros((2,4))
# arr.reshape(2,4)
varr = np.ones((3,3))
print(varr)
print(arr)
print("\n")
print(varr.dtype,varr.shape)
print(arr.dtype,arr.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


float64 (3, 3)
float64 (2, 4)


Given a numpy array str_arr containing strings, write code to convert each string to title case and print the result.

In [4]:
str_arr = np.char.array([["hello","byy"],["gm","gn"]])
print(str_arr.title())


[['Hello' 'Byy']
 ['Gm' 'Gn']]


Create a numpy array containing float values ranging from 1.1 to 5.5. Use astype() to convert it to an array of integers and print the result.

In [5]:
der = np.arange(1.1,5.5)
fer = der.astype(dtype='int64')
fer
#hello

array([1, 2, 3, 4, 5], dtype=int64)

Define a numpy array arr of shape (4, 6) filled with values from 1 to 24. Reshape it to a 2x12 array and print the result.

In [6]:
se = np.arange(1,25).reshape(4,6)
de = se.reshape(2,12)
print(de)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


Compare the performance of iterating through a numpy array using nested loops versus using np.nditer() for a large array (e.g., shape (1000, 1000)).


In [ ]:
we = np.arange(1,1000001).reshape(1000,1000)
for i in np.nditer(we):
    print(i)

Create a 4x4 identity matrix using numpy functions only. Then, multiply it by a randomly generated 4x4 matrix and print the result.


In [17]:
re = np.eye(4,4)
er = np.random.random_sample((4,4))
qw =re.__mul__(er)
qw


array([[0.22410262, 0.        , 0.        , 0.        ],
       [0.        , 0.75861659, 0.        , 0.        ],
       [0.        , 0.        , 0.78931999, 0.        ],
       [0.        , 0.        , 0.        , 0.1051607 ]])

 Given an array `arr` containing the temperature data of a city for a week (7 days), split it into three parts representing morning, afternoon, and evening temperatures respectively. Print each part separately
 [20, 22, 24, 26, 28, 30, 29]
 

In [9]:

arr = np.array([20, 22, 24, 26, 28, 30, 29])
morning_temperatures, afternoon_temperatures, evening_temperatures = np.array_split(arr, [2, 4])
print("Morning temperatures:", morning_temperatures)
print("Afternoon temperatures:", afternoon_temperatures)
print("Evening temperatures:", evening_temperatures)


Morning temperatures: [20 22]
Afternoon temperatures: [24 26]
Evening temperatures: [28 30 29]


Consider an array `arr` representing the quarterly sales data of a company, where each row corresponds to a quarter and each column represents different product categories. Split this array into three parts representing sales data for each product category. Print each part separately.

`After splitting`,<br>
you should have:<br>
Sales data for Product Category 1: [[100, 150, 200], [120, 180, 220]]<br>
Sales data for Product Category 2: [[90, 160, 210], [110, 170, 230]]<br>
Sales data for Product Category 3: Not specified in the sample, but you should provide a similar split.<br>

In [10]:
arr = np.array([[100, 150, 200], [120, 180, 220], [90, 160, 210], [110, 170, 230]])
fr,rf ,gf= np.array_split(arr,[2,4])
print("catgory1 \n",fr)
print("category2 \n",rf)
print("category3 \n",gf)

catgory1 
 [[100 150 200]
 [120 180 220]]
category2 
 [[ 90 160 210]
 [110 170 230]]
category3 
 []


 Given an array `arr` representing the student scores in a class test, split it into 4 parts representing different sections of the class. Then, for each section, find the position where the score 7 fails, if it exists.
 

In [11]:
arr = np.array([7, 8, 6, 7, 9, 7, 8, 5, 7, 7])
x = np.where(arr<=7)
print(x)

(array([0, 2, 3, 5, 7, 8, 9], dtype=int64),)


Suppose you have an array arr representing the daily stock prices of a company over a month. Calculate the daily percentage change in stock prices from the previous day and store it in a new array percentage_change. Then, find the days where the percentage change was greater than 2% and print the indices of those days.
'After calculation, you should print:
Indices of days where the percentage change was greater than 2%.'

In [12]:
arr1 = np.array([100, 102, 105, 98, 100, 105, 110, 112, 115, 120, 118, 122, 125, 130])
percentage_change = (arr1[1:] - arr1[:-1]) / arr1[:-1] * 100 
indices_greater_than_2 = np.where(percentage_change > 2)[0] 
indices_greater_than_2

        


array([ 1,  3,  4,  5,  7,  8, 10, 11, 12], dtype=int64)

Suppose you have two arrays representing the monthly sales data of a company's two branches, where each row corresponds to a month and each column represents different product categories. Concatenate these two arrays vertically to combine the sales data of both branches. Then, reshape the combined array to have 6 rows (representing half-yearly data) and 4 columns (representing product categories). Finally, calculate the total sales for each product category over the half-year period and print the result.

In [13]:
branch1_sales = np.array([[100, 150, 200, 120], [110, 160, 190, 130], [120, 140, 180, 140]])
branch2_sales = np.array([[90, 130, 190, 110], [100, 170, 210, 120], [115, 150, 200, 130]])
branch1_sales.reshape(3,4)
branch2_sales.reshape(3,4)
new_sales = np.vstack((branch1_sales,branch2_sales))
hal = np.sum(new_sales,axis=0)
hal


array([ 635,  900, 1170,  750])

Suppose you have an array representing the monthly revenue generated by a company over the past year. Calculate the average revenue generated per month and then find the months where the revenue was higher than the average. Print the indices of those months.

In [14]:
monthly_revenue = np.array([50000, 55000, 60000, 48000, 52000, 58000, 62000, 53000, 57000, 61000, 59000, 64000])
average = np.sum(monthly_revenue/len(monthly_revenue),axis=0)
df  = np.where(monthly_revenue>average)
print(df)

(array([ 2,  5,  6,  8,  9, 10, 11], dtype=int64),)


Suppose you have an array representing the weekly sales data of a company for two consecutive weeks, where each row corresponds to a week and each column represents different product categories. Calculate the percentage change in sales for each product category from the first week to the second week. Then, identify the product categories where the percentage change is positive and greater than 10%. Print the indices of those product categories.

In [15]:
weekly_sales = np.array([[1000,1200,900,1100],[1100,1300,950,1150]])
perman = (weekly_sales[1]-weekly_sales[0])/10
perman = np.where(perman>=10)
perman

(array([0, 1], dtype=int64),)

In [25]:
def locate_cards(arrays,value):
    desc_array = arrays[::-1]
    
    testing = np.searchsorted(desc_array,value,side="left")
    pos_in_desc = len(arrays)- testing
    return pos_in_desc
arrays=  [10, 2, 4, 5, 6, 7]
value_to_becheked = 7
desc_array1 = sorted(arrays,reverse=True)
test_completed = locate_cards(desc_array1,value_to_becheked)
print(test_completed)


2
